config/routes.rb
Rails.application.routes.draw do

  root to: 'visitors#index'

  post 'requests' => 'requests#create'
  put 'requests' => 'requests#update'
  delete 'requests' => 'requests#destroy'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)


  resources :events
  resources :evaluations, only: [:create, :new]

  devise_for :users, controllers: {
        registrations: 'users/registrations'
      }

  get 'myevents' => 'visitors#my_events'

end

app/models/evaluation.rb
class Evaluation < ActiveRecord::Base
  belongs_to :user
  belongs_to :event

  validates :reading, inclusion: 1..10
  validates :writing, inclusion: 1..10
  validates :listening, inclusion: 1..10

  def sum
  	reading + writing + listening
  end

end

app/controllers/evaluations_controller.rb
class EvaluationsController < ApplicationController
  expose(:evaluation, attributes: :evaluation_params)

  def new
    request = Request.find(params[:request])
    evaluation.event = request.event
    evaluation.user = request.user
  end

  def create
    evaluation.event_id = params[:parameters][:event_id]
    evaluation.user_id = params[:parameters][:user_id]
    if Evaluation.where(event: evaluation.event, user: evaluation.user).empty? && evaluation.save
      flash[:notice] = 'User evaluated successfully'
      redirect_to event_path(evaluation.event)
    else
      flash[:danger] = 'Note already exist'
      render 'evaluations/new'
    end
  end

  private
    def evaluation_params
      params.require(:evaluation).permit(:reading, :writing, :listening)
    end
end

app/helpers/evaluations_helper.rb
module EvaluationsHelper
end

app/views/evaluations/_form.html.haml
= simple_form_for evaluation, url: evaluations_path(evaluation, parameters: {event_id: evaluation.event.id, user_id: evaluation.user_id}) do |f|
  = f.input :reading, error: 'Evaluation must be bettwen 1 and 10'
  = f.input :writing, error: 'Evaluation must be bettwen 1 and 10'
  = f.input :listening, error: 'Evaluation must be bettwen 1 and 10'
  = link_to 'Back', events_path
  = f.submit class: "btn btn-success"

app/views/evaluations/new.html.haml
%h1 Evaluate student
= render 'form'