config/routes.rb
Rails.application.routes.draw do

  root to: 'visitors#index'

  post 'requests' => 'requests#create'
  put 'requests' => 'requests#update'
  delete 'requests' => 'requests#destroy'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)


  resources :events
  resources :evaluations, only: [:create, :new]

  devise_for :users, controllers: {
        registrations: 'users/registrations'
      }

  get 'myevents' => 'visitors#my_events'

end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :requests
  has_many :users, through: :requests
  has_many :evaluations
  belongs_to :user

  def students
    self.users
  end

  def teacher
    self.user
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	expose(:events)
	expose(:event, attributes: :event_params)

 	before_action :authenticate_user!, except: [:show, :index]
	before_action :check_teacher, except: [:show, :index]


	# def new
	# end

	def create
		if event.save
			redirect_to(event)
		else
			render :new
		end
	end

	def edit
	end

	def update
		event.save
		redirect_to(event)
	end

	private

	def event_params
		params.require(:event).permit(:place, :start_time, :user_deadline, :name, :description, :slots)
	end

	def check_teacher
		unless current_user.has_role? :teacher
      redirect_to new_user_session_path
    end
	end

end

app/helpers/events_helper.rb
module EventsHelper
  def evaluation_for_logged_student_exist?(event)
    user_signed_in? && !evaluation(event).nil? && (current_user.has_role? :student)
  end

  def evaluation_for_request_exist?(request)
    !Evaluation.where(event: request.event, user: request.user).empty?
  end

  def evaluation(event)
    Evaluation.where(event_id: event.id, user_id: current_user.id).first
  end
end

app/views/events/_form.html.haml
= simple_form_for event do |f|
	= f.input :place
	= f.input :start_time, as: :string, input_html: { class: 'datetimepicker' }
	= f.input :user_deadline, as: :string, input_html: { class: 'datetimepicker' }
	= f.input :name
	= f.input :description
	= f.input :slots
	= link_to 'Back', events_path
	= f.submit class: "btn btn-success"

app/views/events/edit.html.haml
%h1 Edit Event
= render 'form'

app/views/events/index.html.haml
%h1 Index
-if user_signed_in? && (current_user.has_role? :teacher)
  = link_to 'New Event', new_event_path, class: "btn btn-success"

%table.table.table-condensed
  %thead
    %tr
      %th= 'Event'
      %th= 'Place'
      %th= 'Date'
      %th= 'Deadline'
      %th= 'Slots'
  %tbody
    - events.each do |event|
      %tr
        %td= link_to event.name, event
        %td= event.place
        %td= event.start_time
        %td= event.user_deadline
        %td= event.slots

app/views/events/new.html.haml
%h1 New Event
= render 'form'

app/views/events/show.html.haml
%h1
  = event.name
%h3
  = event.description
%table
  %tr
    %th= t('Place:')
  %tr
    %td= event.place
  %tr
    %th= t('Date:')
  %tr
    %td= event.start_time
  %tr
    %th= t('Request deadline:')
  %tr
    %td= event.user_deadline
  %tr
    %th= t('Empty slots:')
  %tr
    %td= event.slots
  -if evaluation_for_logged_student_exist?(event)
    %tr
      %th= t('Evaluation for reading:')
    %tr
      %td= evaluation(event).reading
    %tr
      %th= t('Evaluation for writing:')
    %tr
      %td= evaluation(event).writing
    %tr
      %th= t('Evaluation for listening:')
    %tr
      %td= evaluation(event).listening

-if user_signed_in? && current_user != event.user

  -if event.students.include?(current_user)
    = link_to 'Undo Request', requests_path(event: event), class: "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' }
  -elsif event.slots == 0
    %h3 Sorry, event is full :(
  -else
    = link_to 'Request for Event', requests_path(event: event), class: "btn btn-success", method: :post

- if current_user == event.user

  = link_to 'Edit', edit_event_path(event), class: "btn btn-success"

  %h1 Requests List
  %br

    .row
      .col-md-6
        %h3 Pending requests
        %table.table.table-condensed
          %thead
            %tr
              %th= 'User'
              %th
              %th
          %tbody
            -event.requests.pending.each do |request|
              %tr
                %td= request.user.email
                %td= link_to("Accept", requests_path(request, obj: request,  status: "accepted", event: event), :method => :put, class: 'btn btn-primary')
                %td= link_to("Reject", requests_path(request, obj: request,  status: "rejected", event: event), :method => :put, class: 'btn btn-danger')
      .col-md-3
        %h3 Accepted requests
        %table.table.table-condensed
          %thead
            %tr
              %th= 'User'
              %th
          %tbody
            -event.requests.accepted.each do |request|
              %tr
                %td= request.user.email
                -if !evaluation_for_request_exist?(request)
                  %td= link_to 'Add note', new_evaluation_path(request: request), class: 'btn btn-danger'
      .col-md-3
        %h3 Rejected requests
        %table.table.table-condensed
          %thead
            %tr
              %th= 'User'
          %tbody
            -event.requests.rejected.each do |request|
              %tr
                %td= request.user.email
- unless user_signed_in?
  = link_to 'Log in to join event!', new_user_session_path, class: 'btn btn-success'